# Generated by Django 6.0.5 on 2026-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full title of the book', max_length=255)),
                ('author', models.CharField(help_text='Name of the author', max_length=255)),
                ('rating', models.FloatField(help_text='Rating from 0.0 to 5.0')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark True to feature this book')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-id'],
            },
        ),
    ]
